name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        # using ${{ github.ref }} returns /refs/tags/TAGNAME instead of just TAGNAME
        name: Get release version
        id: release_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: clevy/amazonlinux2-rust-node:${{ steps.release_version.outputs.tag }}
          cache-from: type=registry,ref=clevy/amazonlinux2-rust-node:buildcache
          cache-to: type=registry,ref=clevy/amazonlinux2-rust-node:buildcache,mode=max
